//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.SaveTool.Data.ProductCommand {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveLogAccountNumberRequest", Namespace="http://wowway.com/Product/Product.API")]
    [System.SerializableAttribute()]
    public partial class SaveLogAccountNumberRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginId {
            get {
                return this.LoginIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginIdField, value) != true)) {
                    this.LoginIdField = value;
                    this.RaisePropertyChanged("LoginId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveLogAccountNumberResponse", Namespace="http://wowway.com/Product/Product.API")]
    [System.SerializableAttribute()]
    public partial class SaveLogAccountNumberResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SaveLogIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SaveLogId {
            get {
                return this.SaveLogIdField;
            }
            set {
                if ((this.SaveLogIdField.Equals(value) != true)) {
                    this.SaveLogIdField = value;
                    this.RaisePropertyChanged("SaveLogId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemFaultException", Namespace="http://wowway.com/Product/Product.API")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.SaveTool.Data.ProductCommand.SecurityFaultException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.SaveTool.Data.ProductCommand.ParameterFaultException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.SaveTool.Data.ProductCommand.DbFaultException))]
    public partial class SystemFaultException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
    [System.SerializableAttribute()]
    public partial class SecurityFaultException : WOW.SaveTool.Data.ProductCommand.SystemFaultException {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParameterFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
    [System.SerializableAttribute()]
    public partial class ParameterFaultException : WOW.SaveTool.Data.ProductCommand.SystemFaultException {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DbFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
    [System.SerializableAttribute()]
    public partial class DbFaultException : WOW.SaveTool.Data.ProductCommand.SystemFaultException {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogCallActionRequest", Namespace="http://wowway.com/Product/Product.API")]
    [System.SerializableAttribute()]
    public partial class LogCallActionRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SaveLogIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallAction {
            get {
                return this.CallActionField;
            }
            set {
                if ((object.ReferenceEquals(this.CallActionField, value) != true)) {
                    this.CallActionField = value;
                    this.RaisePropertyChanged("CallAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SaveLogId {
            get {
                return this.SaveLogIdField;
            }
            set {
                if ((this.SaveLogIdField.Equals(value) != true)) {
                    this.SaveLogIdField = value;
                    this.RaisePropertyChanged("SaveLogId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LogOffersRequest", Namespace="http://wowway.com/Product/Product.API")]
    [System.SerializableAttribute()]
    public partial class LogOffersRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CableOptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CallActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal FiveYearDiscountAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InternetOptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Is12MonthContractField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WOW.SaveTool.Data.ProductCommand.OfferList[] OffersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneOptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SaveLogIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CableOption {
            get {
                return this.CableOptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CableOptionField, value) != true)) {
                    this.CableOptionField = value;
                    this.RaisePropertyChanged("CableOption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallAction {
            get {
                return this.CallActionField;
            }
            set {
                if ((object.ReferenceEquals(this.CallActionField, value) != true)) {
                    this.CallActionField = value;
                    this.RaisePropertyChanged("CallAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal FiveYearDiscountAmount {
            get {
                return this.FiveYearDiscountAmountField;
            }
            set {
                if ((this.FiveYearDiscountAmountField.Equals(value) != true)) {
                    this.FiveYearDiscountAmountField = value;
                    this.RaisePropertyChanged("FiveYearDiscountAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InternetOption {
            get {
                return this.InternetOptionField;
            }
            set {
                if ((object.ReferenceEquals(this.InternetOptionField, value) != true)) {
                    this.InternetOptionField = value;
                    this.RaisePropertyChanged("InternetOption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Is12MonthContract {
            get {
                return this.Is12MonthContractField;
            }
            set {
                if ((this.Is12MonthContractField.Equals(value) != true)) {
                    this.Is12MonthContractField = value;
                    this.RaisePropertyChanged("Is12MonthContract");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WOW.SaveTool.Data.ProductCommand.OfferList[] Offers {
            get {
                return this.OffersField;
            }
            set {
                if ((object.ReferenceEquals(this.OffersField, value) != true)) {
                    this.OffersField = value;
                    this.RaisePropertyChanged("Offers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneOption {
            get {
                return this.PhoneOptionField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneOptionField, value) != true)) {
                    this.PhoneOptionField = value;
                    this.RaisePropertyChanged("PhoneOption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SaveLogId {
            get {
                return this.SaveLogIdField;
            }
            set {
                if ((this.SaveLogIdField.Equals(value) != true)) {
                    this.SaveLogIdField = value;
                    this.RaisePropertyChanged("SaveLogId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OfferList", Namespace="http://wowway.com/Product/Product.API")]
    [System.SerializableAttribute()]
    public partial class OfferList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsAcceptedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsOfferedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OfferTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsAccepted {
            get {
                return this.IsAcceptedField;
            }
            set {
                if ((this.IsAcceptedField.Equals(value) != true)) {
                    this.IsAcceptedField = value;
                    this.RaisePropertyChanged("IsAccepted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsOffered {
            get {
                return this.IsOfferedField;
            }
            set {
                if ((this.IsOfferedField.Equals(value) != true)) {
                    this.IsOfferedField = value;
                    this.RaisePropertyChanged("IsOffered");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OfferType {
            get {
                return this.OfferTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.OfferTypeField, value) != true)) {
                    this.OfferTypeField = value;
                    this.RaisePropertyChanged("OfferType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wowway.com/Product/Product.API", ConfigurationName="ProductCommand.IProductCommand")]
    public interface IProductCommand {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wowway.com/Product/Product.API/IProductCommand/LogAccountNumber", ReplyAction="http://wowway.com/Product/Product.API/IProductCommand/LogAccountNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductCommand.DbFaultException), Action="http://wowway.com/Product/Product.API/IProductCommand/LogAccountNumberDbFaultExce" +
            "ptionFault", Name="DbFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductCommand.SystemFaultException), Action="http://wowway.com/Product/Product.API/IProductCommand/LogAccountNumberSystemFault" +
            "ExceptionFault", Name="SystemFaultException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductCommand.SecurityFaultException), Action="http://wowway.com/Product/Product.API/IProductCommand/LogAccountNumberSecurityFau" +
            "ltExceptionFault", Name="SecurityFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductCommand.ParameterFaultException), Action="http://wowway.com/Product/Product.API/IProductCommand/LogAccountNumberParameterFa" +
            "ultExceptionFault", Name="ParameterFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        WOW.SaveTool.Data.ProductCommand.SaveLogAccountNumberResponse LogAccountNumber(WOW.SaveTool.Data.ProductCommand.SaveLogAccountNumberRequest logAccountNumberRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wowway.com/Product/Product.API/IProductCommand/LogAccountNumber", ReplyAction="http://wowway.com/Product/Product.API/IProductCommand/LogAccountNumberResponse")]
        System.Threading.Tasks.Task<WOW.SaveTool.Data.ProductCommand.SaveLogAccountNumberResponse> LogAccountNumberAsync(WOW.SaveTool.Data.ProductCommand.SaveLogAccountNumberRequest logAccountNumberRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wowway.com/Product/Product.API/IProductCommand/LogCallAction", ReplyAction="http://wowway.com/Product/Product.API/IProductCommand/LogCallActionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductCommand.ParameterFaultException), Action="http://wowway.com/Product/Product.API/IProductCommand/LogCallActionParameterFault" +
            "ExceptionFault", Name="ParameterFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductCommand.SecurityFaultException), Action="http://wowway.com/Product/Product.API/IProductCommand/LogCallActionSecurityFaultE" +
            "xceptionFault", Name="SecurityFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductCommand.DbFaultException), Action="http://wowway.com/Product/Product.API/IProductCommand/LogCallActionDbFaultExcepti" +
            "onFault", Name="DbFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductCommand.SystemFaultException), Action="http://wowway.com/Product/Product.API/IProductCommand/LogCallActionSystemFaultExc" +
            "eptionFault", Name="SystemFaultException")]
        void LogCallAction(WOW.SaveTool.Data.ProductCommand.LogCallActionRequest logCallActionRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wowway.com/Product/Product.API/IProductCommand/LogCallAction", ReplyAction="http://wowway.com/Product/Product.API/IProductCommand/LogCallActionResponse")]
        System.Threading.Tasks.Task LogCallActionAsync(WOW.SaveTool.Data.ProductCommand.LogCallActionRequest logCallActionRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wowway.com/Product/Product.API/IProductCommand/LogOffers", ReplyAction="http://wowway.com/Product/Product.API/IProductCommand/LogOffersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductCommand.DbFaultException), Action="http://wowway.com/Product/Product.API/IProductCommand/LogOffersDbFaultExceptionFa" +
            "ult", Name="DbFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductCommand.SystemFaultException), Action="http://wowway.com/Product/Product.API/IProductCommand/LogOffersSystemFaultExcepti" +
            "onFault", Name="SystemFaultException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductCommand.ParameterFaultException), Action="http://wowway.com/Product/Product.API/IProductCommand/LogOffersParameterFaultExce" +
            "ptionFault", Name="ParameterFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductCommand.SecurityFaultException), Action="http://wowway.com/Product/Product.API/IProductCommand/LogOffersSecurityFaultExcep" +
            "tionFault", Name="SecurityFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        void LogOffers(WOW.SaveTool.Data.ProductCommand.LogOffersRequest logOffersRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wowway.com/Product/Product.API/IProductCommand/LogOffers", ReplyAction="http://wowway.com/Product/Product.API/IProductCommand/LogOffersResponse")]
        System.Threading.Tasks.Task LogOffersAsync(WOW.SaveTool.Data.ProductCommand.LogOffersRequest logOffersRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductCommandChannel : WOW.SaveTool.Data.ProductCommand.IProductCommand, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductCommandClient : System.ServiceModel.ClientBase<WOW.SaveTool.Data.ProductCommand.IProductCommand>, WOW.SaveTool.Data.ProductCommand.IProductCommand {
        
        public ProductCommandClient() {
        }
        
        public ProductCommandClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductCommandClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductCommandClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductCommandClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WOW.SaveTool.Data.ProductCommand.SaveLogAccountNumberResponse LogAccountNumber(WOW.SaveTool.Data.ProductCommand.SaveLogAccountNumberRequest logAccountNumberRequest) {
            return base.Channel.LogAccountNumber(logAccountNumberRequest);
        }
        
        public System.Threading.Tasks.Task<WOW.SaveTool.Data.ProductCommand.SaveLogAccountNumberResponse> LogAccountNumberAsync(WOW.SaveTool.Data.ProductCommand.SaveLogAccountNumberRequest logAccountNumberRequest) {
            return base.Channel.LogAccountNumberAsync(logAccountNumberRequest);
        }
        
        public void LogCallAction(WOW.SaveTool.Data.ProductCommand.LogCallActionRequest logCallActionRequest) {
            base.Channel.LogCallAction(logCallActionRequest);
        }
        
        public System.Threading.Tasks.Task LogCallActionAsync(WOW.SaveTool.Data.ProductCommand.LogCallActionRequest logCallActionRequest) {
            return base.Channel.LogCallActionAsync(logCallActionRequest);
        }
        
        public void LogOffers(WOW.SaveTool.Data.ProductCommand.LogOffersRequest logOffersRequest) {
            base.Channel.LogOffers(logOffersRequest);
        }
        
        public System.Threading.Tasks.Task LogOffersAsync(WOW.SaveTool.Data.ProductCommand.LogOffersRequest logOffersRequest) {
            return base.Channel.LogOffersAsync(logOffersRequest);
        }
    }
}
