//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WOW.SaveTool.Data.ProductQuery {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EtfRequest", Namespace="http://wowway.com/Product/Product.API")]
    [System.SerializableAttribute()]
    public partial class EtfRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WOW.SaveTool.Data.ProductQuery.Package[] AccountPackageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime EndDateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WOW.SaveTool.Data.ProductQuery.Package[] AccountPackage {
            get {
                return this.AccountPackageField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountPackageField, value) != true)) {
                    this.AccountPackageField = value;
                    this.RaisePropertyChanged("AccountPackage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EndDate {
            get {
                return this.EndDateField;
            }
            set {
                if ((this.EndDateField.Equals(value) != true)) {
                    this.EndDateField = value;
                    this.RaisePropertyChanged("EndDate");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Package", Namespace="http://wowway.com/Product/Product.API")]
    [System.SerializableAttribute()]
    public partial class Package : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime StartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime StartDate {
            get {
                return this.StartDateField;
            }
            set {
                if ((this.StartDateField.Equals(value) != true)) {
                    this.StartDateField = value;
                    this.RaisePropertyChanged("StartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EtfResponse", Namespace="http://wowway.com/Product/Product.API")]
    [System.SerializableAttribute()]
    public partial class EtfResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal EtfAmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal EtfAmount {
            get {
                return this.EtfAmountField;
            }
            set {
                if ((this.EtfAmountField.Equals(value) != true)) {
                    this.EtfAmountField = value;
                    this.RaisePropertyChanged("EtfAmount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerRatingRequest", Namespace="http://wowway.com/Product/Product.API")]
    [System.SerializableAttribute()]
    public partial class CustomerRatingRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemFaultException", Namespace="http://wowway.com/Product/Product.API")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.SaveTool.Data.ProductQuery.DbFaultException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.SaveTool.Data.ProductQuery.SecurityFaultException))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(WOW.SaveTool.Data.ProductQuery.ParameterFaultException))]
    public partial class SystemFaultException : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorCode {
            get {
                return this.ErrorCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorCodeField, value) != true)) {
                    this.ErrorCodeField = value;
                    this.RaisePropertyChanged("ErrorCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DbFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
    [System.SerializableAttribute()]
    public partial class DbFaultException : WOW.SaveTool.Data.ProductQuery.SystemFaultException {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SecurityFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
    [System.SerializableAttribute()]
    public partial class SecurityFaultException : WOW.SaveTool.Data.ProductQuery.SystemFaultException {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ParameterFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
    [System.SerializableAttribute()]
    public partial class ParameterFaultException : WOW.SaveTool.Data.ProductQuery.SystemFaultException {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOfferRequest", Namespace="http://wowway.com/Product/Product.API")]
    [System.SerializableAttribute()]
    public partial class GetOfferRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WOW.SaveTool.Data.ProductQuery.Package[] AccountPackageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsInternetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MarketIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WOW.SaveTool.Data.ProductQuery.EnumsOfferGroup OfferGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SaveLogIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StarRatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TenureField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WOW.SaveTool.Data.ProductQuery.Package[] AccountPackage {
            get {
                return this.AccountPackageField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountPackageField, value) != true)) {
                    this.AccountPackageField = value;
                    this.RaisePropertyChanged("AccountPackage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCable {
            get {
                return this.IsCableField;
            }
            set {
                if ((this.IsCableField.Equals(value) != true)) {
                    this.IsCableField = value;
                    this.RaisePropertyChanged("IsCable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInternet {
            get {
                return this.IsInternetField;
            }
            set {
                if ((this.IsInternetField.Equals(value) != true)) {
                    this.IsInternetField = value;
                    this.RaisePropertyChanged("IsInternet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPhone {
            get {
                return this.IsPhoneField;
            }
            set {
                if ((this.IsPhoneField.Equals(value) != true)) {
                    this.IsPhoneField = value;
                    this.RaisePropertyChanged("IsPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarketId {
            get {
                return this.MarketIdField;
            }
            set {
                if ((this.MarketIdField.Equals(value) != true)) {
                    this.MarketIdField = value;
                    this.RaisePropertyChanged("MarketId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WOW.SaveTool.Data.ProductQuery.EnumsOfferGroup OfferGroup {
            get {
                return this.OfferGroupField;
            }
            set {
                if ((this.OfferGroupField.Equals(value) != true)) {
                    this.OfferGroupField = value;
                    this.RaisePropertyChanged("OfferGroup");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SaveLogId {
            get {
                return this.SaveLogIdField;
            }
            set {
                if ((this.SaveLogIdField.Equals(value) != true)) {
                    this.SaveLogIdField = value;
                    this.RaisePropertyChanged("SaveLogId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StarRating {
            get {
                return this.StarRatingField;
            }
            set {
                if ((this.StarRatingField.Equals(value) != true)) {
                    this.StarRatingField = value;
                    this.RaisePropertyChanged("StarRating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tenure {
            get {
                return this.TenureField;
            }
            set {
                if ((this.TenureField.Equals(value) != true)) {
                    this.TenureField = value;
                    this.RaisePropertyChanged("Tenure");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.OfferGroup", Namespace="http://wowway.com/Product/Product.API")]
    public enum EnumsOfferGroup : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FrontCounter = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CallCenter = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Loyalty = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetOfferResponse", Namespace="http://wowway.com/Product/Product.API")]
    [System.SerializableAttribute()]
    public partial class GetOfferResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WOW.SaveTool.Data.ProductQuery.Offers[] OffersField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WOW.SaveTool.Data.ProductQuery.Offers[] Offers {
            get {
                return this.OffersField;
            }
            set {
                if ((object.ReferenceEquals(this.OffersField, value) != true)) {
                    this.OffersField = value;
                    this.RaisePropertyChanged("Offers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Offers", Namespace="http://wowway.com/Product/Product.API")]
    [System.SerializableAttribute()]
    public partial class Offers : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WOW.SaveTool.Data.ProductQuery.EnumsDiscountType DiscountTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WOW.SaveTool.Data.ProductQuery.EnumsDiscountType DiscountType {
            get {
                return this.DiscountTypeField;
            }
            set {
                if ((this.DiscountTypeField.Equals(value) != true)) {
                    this.DiscountTypeField = value;
                    this.RaisePropertyChanged("DiscountType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Enums.DiscountType", Namespace="http://wowway.com/Product/Product.API")]
    public enum EnumsDiscountType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GoodWill = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Proactive = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Discount1 = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Contract = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Loyalty1 = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Loyalty2 = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TrasferToLoyalty = 7,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRateIncreaseRequest", Namespace="http://wowway.com/Product/Product.API")]
    [System.SerializableAttribute()]
    public partial class GetRateIncreaseRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WOW.SaveTool.Data.ProductQuery.Package[] AccountPackageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsCableField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsInternetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MarketIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WOW.SaveTool.Data.ProductQuery.Package[] AccountPackage {
            get {
                return this.AccountPackageField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountPackageField, value) != true)) {
                    this.AccountPackageField = value;
                    this.RaisePropertyChanged("AccountPackage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCable {
            get {
                return this.IsCableField;
            }
            set {
                if ((this.IsCableField.Equals(value) != true)) {
                    this.IsCableField = value;
                    this.RaisePropertyChanged("IsCable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsInternet {
            get {
                return this.IsInternetField;
            }
            set {
                if ((this.IsInternetField.Equals(value) != true)) {
                    this.IsInternetField = value;
                    this.RaisePropertyChanged("IsInternet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsPhone {
            get {
                return this.IsPhoneField;
            }
            set {
                if ((this.IsPhoneField.Equals(value) != true)) {
                    this.IsPhoneField = value;
                    this.RaisePropertyChanged("IsPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MarketId {
            get {
                return this.MarketIdField;
            }
            set {
                if ((this.MarketIdField.Equals(value) != true)) {
                    this.MarketIdField = value;
                    this.RaisePropertyChanged("MarketId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RateIncreaseResponse", Namespace="http://wowway.com/Product/Product.API")]
    [System.SerializableAttribute()]
    public partial class RateIncreaseResponse : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://wowway.com/Product/Product.API", ConfigurationName="ProductQuery.IProductQuery")]
    public interface IProductQuery {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wowway.com/Product/Product.API/IProductQuery/GetEtfByPackage", ReplyAction="http://wowway.com/Product/Product.API/IProductQuery/GetEtfByPackageResponse")]
        WOW.SaveTool.Data.ProductQuery.EtfResponse GetEtfByPackage(WOW.SaveTool.Data.ProductQuery.EtfRequest etfRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wowway.com/Product/Product.API/IProductQuery/GetEtfByPackage", ReplyAction="http://wowway.com/Product/Product.API/IProductQuery/GetEtfByPackageResponse")]
        System.Threading.Tasks.Task<WOW.SaveTool.Data.ProductQuery.EtfResponse> GetEtfByPackageAsync(WOW.SaveTool.Data.ProductQuery.EtfRequest etfRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wowway.com/Product/Product.API/IProductQuery/GetCustomerRating", ReplyAction="http://wowway.com/Product/Product.API/IProductQuery/GetCustomerRatingResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductQuery.ParameterFaultException), Action="http://wowway.com/Product/Product.API/IProductQuery/GetCustomerRatingParameterFau" +
            "ltExceptionFault", Name="ParameterFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductQuery.DbFaultException), Action="http://wowway.com/Product/Product.API/IProductQuery/GetCustomerRatingDbFaultExcep" +
            "tionFault", Name="DbFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductQuery.SecurityFaultException), Action="http://wowway.com/Product/Product.API/IProductQuery/GetCustomerRatingSecurityFaul" +
            "tExceptionFault", Name="SecurityFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductQuery.SystemFaultException), Action="http://wowway.com/Product/Product.API/IProductQuery/GetCustomerRatingSystemFaultE" +
            "xceptionFault", Name="SystemFaultException")]
        int GetCustomerRating(WOW.SaveTool.Data.ProductQuery.CustomerRatingRequest customerRatingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wowway.com/Product/Product.API/IProductQuery/GetCustomerRating", ReplyAction="http://wowway.com/Product/Product.API/IProductQuery/GetCustomerRatingResponse")]
        System.Threading.Tasks.Task<int> GetCustomerRatingAsync(WOW.SaveTool.Data.ProductQuery.CustomerRatingRequest customerRatingRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wowway.com/Product/Product.API/IProductQuery/GetOffers", ReplyAction="http://wowway.com/Product/Product.API/IProductQuery/GetOffersResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductQuery.SystemFaultException), Action="http://wowway.com/Product/Product.API/IProductQuery/GetOffersSystemFaultException" +
            "Fault", Name="SystemFaultException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductQuery.ParameterFaultException), Action="http://wowway.com/Product/Product.API/IProductQuery/GetOffersParameterFaultExcept" +
            "ionFault", Name="ParameterFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductQuery.DbFaultException), Action="http://wowway.com/Product/Product.API/IProductQuery/GetOffersDbFaultExceptionFaul" +
            "t", Name="DbFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductQuery.SecurityFaultException), Action="http://wowway.com/Product/Product.API/IProductQuery/GetOffersSecurityFaultExcepti" +
            "onFault", Name="SecurityFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        WOW.SaveTool.Data.ProductQuery.GetOfferResponse GetOffers(WOW.SaveTool.Data.ProductQuery.GetOfferRequest getOfferRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wowway.com/Product/Product.API/IProductQuery/GetOffers", ReplyAction="http://wowway.com/Product/Product.API/IProductQuery/GetOffersResponse")]
        System.Threading.Tasks.Task<WOW.SaveTool.Data.ProductQuery.GetOfferResponse> GetOffersAsync(WOW.SaveTool.Data.ProductQuery.GetOfferRequest getOfferRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wowway.com/Product/Product.API/IProductQuery/GetRateIncrease", ReplyAction="http://wowway.com/Product/Product.API/IProductQuery/GetRateIncreaseResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductQuery.SecurityFaultException), Action="http://wowway.com/Product/Product.API/IProductQuery/GetRateIncreaseSecurityFaultE" +
            "xceptionFault", Name="SecurityFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductQuery.SystemFaultException), Action="http://wowway.com/Product/Product.API/IProductQuery/GetRateIncreaseSystemFaultExc" +
            "eptionFault", Name="SystemFaultException")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductQuery.DbFaultException), Action="http://wowway.com/Product/Product.API/IProductQuery/GetRateIncreaseDbFaultExcepti" +
            "onFault", Name="DbFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        [System.ServiceModel.FaultContractAttribute(typeof(WOW.SaveTool.Data.ProductQuery.ParameterFaultException), Action="http://wowway.com/Product/Product.API/IProductQuery/GetRateIncreaseParameterFault" +
            "ExceptionFault", Name="ParameterFaultException", Namespace="http://schemas.datacontract.org/2004/07/WOW.Product.Contract.Fault")]
        WOW.SaveTool.Data.ProductQuery.RateIncreaseResponse GetRateIncrease(WOW.SaveTool.Data.ProductQuery.GetRateIncreaseRequest rateIncreaseRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://wowway.com/Product/Product.API/IProductQuery/GetRateIncrease", ReplyAction="http://wowway.com/Product/Product.API/IProductQuery/GetRateIncreaseResponse")]
        System.Threading.Tasks.Task<WOW.SaveTool.Data.ProductQuery.RateIncreaseResponse> GetRateIncreaseAsync(WOW.SaveTool.Data.ProductQuery.GetRateIncreaseRequest rateIncreaseRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductQueryChannel : WOW.SaveTool.Data.ProductQuery.IProductQuery, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductQueryClient : System.ServiceModel.ClientBase<WOW.SaveTool.Data.ProductQuery.IProductQuery>, WOW.SaveTool.Data.ProductQuery.IProductQuery {
        
        public ProductQueryClient() {
        }
        
        public ProductQueryClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductQueryClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductQueryClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductQueryClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WOW.SaveTool.Data.ProductQuery.EtfResponse GetEtfByPackage(WOW.SaveTool.Data.ProductQuery.EtfRequest etfRequest) {
            return base.Channel.GetEtfByPackage(etfRequest);
        }
        
        public System.Threading.Tasks.Task<WOW.SaveTool.Data.ProductQuery.EtfResponse> GetEtfByPackageAsync(WOW.SaveTool.Data.ProductQuery.EtfRequest etfRequest) {
            return base.Channel.GetEtfByPackageAsync(etfRequest);
        }
        
        public int GetCustomerRating(WOW.SaveTool.Data.ProductQuery.CustomerRatingRequest customerRatingRequest) {
            return base.Channel.GetCustomerRating(customerRatingRequest);
        }
        
        public System.Threading.Tasks.Task<int> GetCustomerRatingAsync(WOW.SaveTool.Data.ProductQuery.CustomerRatingRequest customerRatingRequest) {
            return base.Channel.GetCustomerRatingAsync(customerRatingRequest);
        }
        
        public WOW.SaveTool.Data.ProductQuery.GetOfferResponse GetOffers(WOW.SaveTool.Data.ProductQuery.GetOfferRequest getOfferRequest) {
            return base.Channel.GetOffers(getOfferRequest);
        }
        
        public System.Threading.Tasks.Task<WOW.SaveTool.Data.ProductQuery.GetOfferResponse> GetOffersAsync(WOW.SaveTool.Data.ProductQuery.GetOfferRequest getOfferRequest) {
            return base.Channel.GetOffersAsync(getOfferRequest);
        }
        
        public WOW.SaveTool.Data.ProductQuery.RateIncreaseResponse GetRateIncrease(WOW.SaveTool.Data.ProductQuery.GetRateIncreaseRequest rateIncreaseRequest) {
            return base.Channel.GetRateIncrease(rateIncreaseRequest);
        }
        
        public System.Threading.Tasks.Task<WOW.SaveTool.Data.ProductQuery.RateIncreaseResponse> GetRateIncreaseAsync(WOW.SaveTool.Data.ProductQuery.GetRateIncreaseRequest rateIncreaseRequest) {
            return base.Channel.GetRateIncreaseAsync(rateIncreaseRequest);
        }
    }
}
